/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as CommandRouteImport } from './routes/_command'
import { Route as CitizenRouteImport } from './routes/_citizen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandCommandIndexRouteImport } from './routes/_command.command.index'
import { Route as CitizenCitizenIndexRouteImport } from './routes/_citizen.citizen.index'
import { Route as CommandCommandThreatFeedRouteImport } from './routes/_command.command.threat-feed'
import { Route as CommandCommandReportsRouteImport } from './routes/_command.command.reports'
import { Route as CommandCommandNetworkRouteImport } from './routes/_command.command.network'
import { Route as CommandCommandInvestigationsRouteImport } from './routes/_command.command.investigations'
import { Route as CommandCommandGeoRouteImport } from './routes/_command.command.geo'
import { Route as CommandCommandEvidenceRouteImport } from './routes/_command.command.evidence'
import { Route as CommandCommandCurrencyRouteImport } from './routes/_command.command.currency'
import { Route as CommandCommandAuditRouteImport } from './routes/_command.command.audit'
import { Route as CommandCommandAnalyticsRouteImport } from './routes/_command.command.analytics'
import { Route as CommandCommandAiHealthRouteImport } from './routes/_command.command.ai-health'
import { Route as CommandCommandAdminRouteImport } from './routes/_command.command.admin'
import { Route as CitizenCitizenReportRouteImport } from './routes/_citizen.citizen.report'
import { Route as CitizenCitizenLearnRouteImport } from './routes/_citizen.citizen.learn'
import { Route as CitizenCitizenCoolingOffRouteImport } from './routes/_citizen.citizen.cooling-off'
import { Route as CitizenCitizenAnalyzeVoiceRouteImport } from './routes/_citizen.citizen.analyze.voice'
import { Route as CitizenCitizenAnalyzeImageRouteImport } from './routes/_citizen.citizen.analyze.image'
import { Route as CitizenCitizenAnalyzeCurrencyRouteImport } from './routes/_citizen.citizen.analyze.currency'
import { Route as CitizenCitizenAnalyzeChatRouteImport } from './routes/_citizen.citizen.analyze.chat'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/_command',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/_citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCommandIndexRoute = CommandCommandIndexRouteImport.update({
  id: '/command/',
  path: '/command/',
  getParentRoute: () => CommandRoute,
} as any)
const CitizenCitizenIndexRoute = CitizenCitizenIndexRouteImport.update({
  id: '/citizen/',
  path: '/citizen/',
  getParentRoute: () => CitizenRoute,
} as any)
const CommandCommandThreatFeedRoute =
  CommandCommandThreatFeedRouteImport.update({
    id: '/command/threat-feed',
    path: '/command/threat-feed',
    getParentRoute: () => CommandRoute,
  } as any)
const CommandCommandReportsRoute = CommandCommandReportsRouteImport.update({
  id: '/command/reports',
  path: '/command/reports',
  getParentRoute: () => CommandRoute,
} as any)
const CommandCommandNetworkRoute = CommandCommandNetworkRouteImport.update({
  id: '/command/network',
  path: '/command/network',
  getParentRoute: () => CommandRoute,
} as any)
const CommandCommandInvestigationsRoute =
  CommandCommandInvestigationsRouteImport.update({
    id: '/command/investigations',
    path: '/command/investigations',
    getParentRoute: () => CommandRoute,
  } as any)
const CommandCommandGeoRoute = CommandCommandGeoRouteImport.update({
  id: '/command/geo',
  path: '/command/geo',
  getParentRoute: () => CommandRoute,
} as any)
const CommandCommandEvidenceRoute = CommandCommandEvidenceRouteImport.update({
  id: '/command/evidence',
  path: '/command/evidence',
  getParentRoute: () => CommandRoute,
} as any)
const CommandCommandCurrencyRoute = CommandCommandCurrencyRouteImport.update({
  id: '/command/currency',
  path: '/command/currency',
  getParentRoute: () => CommandRoute,
} as any)
const CommandCommandAuditRoute = CommandCommandAuditRouteImport.update({
  id: '/command/audit',
  path: '/command/audit',
  getParentRoute: () => CommandRoute,
} as any)
const CommandCommandAnalyticsRoute = CommandCommandAnalyticsRouteImport.update({
  id: '/command/analytics',
  path: '/command/analytics',
  getParentRoute: () => CommandRoute,
} as any)
const CommandCommandAiHealthRoute = CommandCommandAiHealthRouteImport.update({
  id: '/command/ai-health',
  path: '/command/ai-health',
  getParentRoute: () => CommandRoute,
} as any)
const CommandCommandAdminRoute = CommandCommandAdminRouteImport.update({
  id: '/command/admin',
  path: '/command/admin',
  getParentRoute: () => CommandRoute,
} as any)
const CitizenCitizenReportRoute = CitizenCitizenReportRouteImport.update({
  id: '/citizen/report',
  path: '/citizen/report',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenCitizenLearnRoute = CitizenCitizenLearnRouteImport.update({
  id: '/citizen/learn',
  path: '/citizen/learn',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenCitizenCoolingOffRoute =
  CitizenCitizenCoolingOffRouteImport.update({
    id: '/citizen/cooling-off',
    path: '/citizen/cooling-off',
    getParentRoute: () => CitizenRoute,
  } as any)
const CitizenCitizenAnalyzeVoiceRoute =
  CitizenCitizenAnalyzeVoiceRouteImport.update({
    id: '/citizen/analyze/voice',
    path: '/citizen/analyze/voice',
    getParentRoute: () => CitizenRoute,
  } as any)
const CitizenCitizenAnalyzeImageRoute =
  CitizenCitizenAnalyzeImageRouteImport.update({
    id: '/citizen/analyze/image',
    path: '/citizen/analyze/image',
    getParentRoute: () => CitizenRoute,
  } as any)
const CitizenCitizenAnalyzeCurrencyRoute =
  CitizenCitizenAnalyzeCurrencyRouteImport.update({
    id: '/citizen/analyze/currency',
    path: '/citizen/analyze/currency',
    getParentRoute: () => CitizenRoute,
  } as any)
const CitizenCitizenAnalyzeChatRoute =
  CitizenCitizenAnalyzeChatRouteImport.update({
    id: '/citizen/analyze/chat',
    path: '/citizen/analyze/chat',
    getParentRoute: () => CitizenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/demo': typeof DemoRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/transparency': typeof TransparencyRoute
  '/citizen/cooling-off': typeof CitizenCitizenCoolingOffRoute
  '/citizen/learn': typeof CitizenCitizenLearnRoute
  '/citizen/report': typeof CitizenCitizenReportRoute
  '/command/admin': typeof CommandCommandAdminRoute
  '/command/ai-health': typeof CommandCommandAiHealthRoute
  '/command/analytics': typeof CommandCommandAnalyticsRoute
  '/command/audit': typeof CommandCommandAuditRoute
  '/command/currency': typeof CommandCommandCurrencyRoute
  '/command/evidence': typeof CommandCommandEvidenceRoute
  '/command/geo': typeof CommandCommandGeoRoute
  '/command/investigations': typeof CommandCommandInvestigationsRoute
  '/command/network': typeof CommandCommandNetworkRoute
  '/command/reports': typeof CommandCommandReportsRoute
  '/command/threat-feed': typeof CommandCommandThreatFeedRoute
  '/citizen/': typeof CitizenCitizenIndexRoute
  '/command/': typeof CommandCommandIndexRoute
  '/citizen/analyze/chat': typeof CitizenCitizenAnalyzeChatRoute
  '/citizen/analyze/currency': typeof CitizenCitizenAnalyzeCurrencyRoute
  '/citizen/analyze/image': typeof CitizenCitizenAnalyzeImageRoute
  '/citizen/analyze/voice': typeof CitizenCitizenAnalyzeVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/demo': typeof DemoRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/transparency': typeof TransparencyRoute
  '/citizen/cooling-off': typeof CitizenCitizenCoolingOffRoute
  '/citizen/learn': typeof CitizenCitizenLearnRoute
  '/citizen/report': typeof CitizenCitizenReportRoute
  '/command/admin': typeof CommandCommandAdminRoute
  '/command/ai-health': typeof CommandCommandAiHealthRoute
  '/command/analytics': typeof CommandCommandAnalyticsRoute
  '/command/audit': typeof CommandCommandAuditRoute
  '/command/currency': typeof CommandCommandCurrencyRoute
  '/command/evidence': typeof CommandCommandEvidenceRoute
  '/command/geo': typeof CommandCommandGeoRoute
  '/command/investigations': typeof CommandCommandInvestigationsRoute
  '/command/network': typeof CommandCommandNetworkRoute
  '/command/reports': typeof CommandCommandReportsRoute
  '/command/threat-feed': typeof CommandCommandThreatFeedRoute
  '/citizen': typeof CitizenCitizenIndexRoute
  '/command': typeof CommandCommandIndexRoute
  '/citizen/analyze/chat': typeof CitizenCitizenAnalyzeChatRoute
  '/citizen/analyze/currency': typeof CitizenCitizenAnalyzeCurrencyRoute
  '/citizen/analyze/image': typeof CitizenCitizenAnalyzeImageRoute
  '/citizen/analyze/voice': typeof CitizenCitizenAnalyzeVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_citizen': typeof CitizenRouteWithChildren
  '/_command': typeof CommandRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/demo': typeof DemoRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/transparency': typeof TransparencyRoute
  '/_citizen/citizen/cooling-off': typeof CitizenCitizenCoolingOffRoute
  '/_citizen/citizen/learn': typeof CitizenCitizenLearnRoute
  '/_citizen/citizen/report': typeof CitizenCitizenReportRoute
  '/_command/command/admin': typeof CommandCommandAdminRoute
  '/_command/command/ai-health': typeof CommandCommandAiHealthRoute
  '/_command/command/analytics': typeof CommandCommandAnalyticsRoute
  '/_command/command/audit': typeof CommandCommandAuditRoute
  '/_command/command/currency': typeof CommandCommandCurrencyRoute
  '/_command/command/evidence': typeof CommandCommandEvidenceRoute
  '/_command/command/geo': typeof CommandCommandGeoRoute
  '/_command/command/investigations': typeof CommandCommandInvestigationsRoute
  '/_command/command/network': typeof CommandCommandNetworkRoute
  '/_command/command/reports': typeof CommandCommandReportsRoute
  '/_command/command/threat-feed': typeof CommandCommandThreatFeedRoute
  '/_citizen/citizen/': typeof CitizenCitizenIndexRoute
  '/_command/command/': typeof CommandCommandIndexRoute
  '/_citizen/citizen/analyze/chat': typeof CitizenCitizenAnalyzeChatRoute
  '/_citizen/citizen/analyze/currency': typeof CitizenCitizenAnalyzeCurrencyRoute
  '/_citizen/citizen/analyze/image': typeof CitizenCitizenAnalyzeImageRoute
  '/_citizen/citizen/analyze/voice': typeof CitizenCitizenAnalyzeVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/demo'
    | '/help'
    | '/privacy'
    | '/settings'
    | '/status'
    | '/transparency'
    | '/citizen/cooling-off'
    | '/citizen/learn'
    | '/citizen/report'
    | '/command/admin'
    | '/command/ai-health'
    | '/command/analytics'
    | '/command/audit'
    | '/command/currency'
    | '/command/evidence'
    | '/command/geo'
    | '/command/investigations'
    | '/command/network'
    | '/command/reports'
    | '/command/threat-feed'
    | '/citizen/'
    | '/command/'
    | '/citizen/analyze/chat'
    | '/citizen/analyze/currency'
    | '/citizen/analyze/image'
    | '/citizen/analyze/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/demo'
    | '/help'
    | '/privacy'
    | '/settings'
    | '/status'
    | '/transparency'
    | '/citizen/cooling-off'
    | '/citizen/learn'
    | '/citizen/report'
    | '/command/admin'
    | '/command/ai-health'
    | '/command/analytics'
    | '/command/audit'
    | '/command/currency'
    | '/command/evidence'
    | '/command/geo'
    | '/command/investigations'
    | '/command/network'
    | '/command/reports'
    | '/command/threat-feed'
    | '/citizen'
    | '/command'
    | '/citizen/analyze/chat'
    | '/citizen/analyze/currency'
    | '/citizen/analyze/image'
    | '/citizen/analyze/voice'
  id:
    | '__root__'
    | '/'
    | '/_citizen'
    | '/_command'
    | '/accessibility'
    | '/demo'
    | '/help'
    | '/privacy'
    | '/settings'
    | '/status'
    | '/transparency'
    | '/_citizen/citizen/cooling-off'
    | '/_citizen/citizen/learn'
    | '/_citizen/citizen/report'
    | '/_command/command/admin'
    | '/_command/command/ai-health'
    | '/_command/command/analytics'
    | '/_command/command/audit'
    | '/_command/command/currency'
    | '/_command/command/evidence'
    | '/_command/command/geo'
    | '/_command/command/investigations'
    | '/_command/command/network'
    | '/_command/command/reports'
    | '/_command/command/threat-feed'
    | '/_citizen/citizen/'
    | '/_command/command/'
    | '/_citizen/citizen/analyze/chat'
    | '/_citizen/citizen/analyze/currency'
    | '/_citizen/citizen/analyze/image'
    | '/_citizen/citizen/analyze/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRouteWithChildren
  CommandRoute: typeof CommandRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  DemoRoute: typeof DemoRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  TransparencyRoute: typeof TransparencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_command': {
      id: '/_command'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_citizen': {
      id: '/_citizen'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_command/command/': {
      id: '/_command/command/'
      path: '/command'
      fullPath: '/command/'
      preLoaderRoute: typeof CommandCommandIndexRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_citizen/citizen/': {
      id: '/_citizen/citizen/'
      path: '/citizen'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenCitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/_command/command/threat-feed': {
      id: '/_command/command/threat-feed'
      path: '/command/threat-feed'
      fullPath: '/command/threat-feed'
      preLoaderRoute: typeof CommandCommandThreatFeedRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_command/command/reports': {
      id: '/_command/command/reports'
      path: '/command/reports'
      fullPath: '/command/reports'
      preLoaderRoute: typeof CommandCommandReportsRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_command/command/network': {
      id: '/_command/command/network'
      path: '/command/network'
      fullPath: '/command/network'
      preLoaderRoute: typeof CommandCommandNetworkRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_command/command/investigations': {
      id: '/_command/command/investigations'
      path: '/command/investigations'
      fullPath: '/command/investigations'
      preLoaderRoute: typeof CommandCommandInvestigationsRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_command/command/geo': {
      id: '/_command/command/geo'
      path: '/command/geo'
      fullPath: '/command/geo'
      preLoaderRoute: typeof CommandCommandGeoRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_command/command/evidence': {
      id: '/_command/command/evidence'
      path: '/command/evidence'
      fullPath: '/command/evidence'
      preLoaderRoute: typeof CommandCommandEvidenceRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_command/command/currency': {
      id: '/_command/command/currency'
      path: '/command/currency'
      fullPath: '/command/currency'
      preLoaderRoute: typeof CommandCommandCurrencyRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_command/command/audit': {
      id: '/_command/command/audit'
      path: '/command/audit'
      fullPath: '/command/audit'
      preLoaderRoute: typeof CommandCommandAuditRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_command/command/analytics': {
      id: '/_command/command/analytics'
      path: '/command/analytics'
      fullPath: '/command/analytics'
      preLoaderRoute: typeof CommandCommandAnalyticsRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_command/command/ai-health': {
      id: '/_command/command/ai-health'
      path: '/command/ai-health'
      fullPath: '/command/ai-health'
      preLoaderRoute: typeof CommandCommandAiHealthRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_command/command/admin': {
      id: '/_command/command/admin'
      path: '/command/admin'
      fullPath: '/command/admin'
      preLoaderRoute: typeof CommandCommandAdminRouteImport
      parentRoute: typeof CommandRoute
    }
    '/_citizen/citizen/report': {
      id: '/_citizen/citizen/report'
      path: '/citizen/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenCitizenReportRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/_citizen/citizen/learn': {
      id: '/_citizen/citizen/learn'
      path: '/citizen/learn'
      fullPath: '/citizen/learn'
      preLoaderRoute: typeof CitizenCitizenLearnRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/_citizen/citizen/cooling-off': {
      id: '/_citizen/citizen/cooling-off'
      path: '/citizen/cooling-off'
      fullPath: '/citizen/cooling-off'
      preLoaderRoute: typeof CitizenCitizenCoolingOffRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/_citizen/citizen/analyze/voice': {
      id: '/_citizen/citizen/analyze/voice'
      path: '/citizen/analyze/voice'
      fullPath: '/citizen/analyze/voice'
      preLoaderRoute: typeof CitizenCitizenAnalyzeVoiceRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/_citizen/citizen/analyze/image': {
      id: '/_citizen/citizen/analyze/image'
      path: '/citizen/analyze/image'
      fullPath: '/citizen/analyze/image'
      preLoaderRoute: typeof CitizenCitizenAnalyzeImageRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/_citizen/citizen/analyze/currency': {
      id: '/_citizen/citizen/analyze/currency'
      path: '/citizen/analyze/currency'
      fullPath: '/citizen/analyze/currency'
      preLoaderRoute: typeof CitizenCitizenAnalyzeCurrencyRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/_citizen/citizen/analyze/chat': {
      id: '/_citizen/citizen/analyze/chat'
      path: '/citizen/analyze/chat'
      fullPath: '/citizen/analyze/chat'
      preLoaderRoute: typeof CitizenCitizenAnalyzeChatRouteImport
      parentRoute: typeof CitizenRoute
    }
  }
}

interface CitizenRouteChildren {
  CitizenCitizenCoolingOffRoute: typeof CitizenCitizenCoolingOffRoute
  CitizenCitizenLearnRoute: typeof CitizenCitizenLearnRoute
  CitizenCitizenReportRoute: typeof CitizenCitizenReportRoute
  CitizenCitizenIndexRoute: typeof CitizenCitizenIndexRoute
  CitizenCitizenAnalyzeChatRoute: typeof CitizenCitizenAnalyzeChatRoute
  CitizenCitizenAnalyzeCurrencyRoute: typeof CitizenCitizenAnalyzeCurrencyRoute
  CitizenCitizenAnalyzeImageRoute: typeof CitizenCitizenAnalyzeImageRoute
  CitizenCitizenAnalyzeVoiceRoute: typeof CitizenCitizenAnalyzeVoiceRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenCitizenCoolingOffRoute: CitizenCitizenCoolingOffRoute,
  CitizenCitizenLearnRoute: CitizenCitizenLearnRoute,
  CitizenCitizenReportRoute: CitizenCitizenReportRoute,
  CitizenCitizenIndexRoute: CitizenCitizenIndexRoute,
  CitizenCitizenAnalyzeChatRoute: CitizenCitizenAnalyzeChatRoute,
  CitizenCitizenAnalyzeCurrencyRoute: CitizenCitizenAnalyzeCurrencyRoute,
  CitizenCitizenAnalyzeImageRoute: CitizenCitizenAnalyzeImageRoute,
  CitizenCitizenAnalyzeVoiceRoute: CitizenCitizenAnalyzeVoiceRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface CommandRouteChildren {
  CommandCommandAdminRoute: typeof CommandCommandAdminRoute
  CommandCommandAiHealthRoute: typeof CommandCommandAiHealthRoute
  CommandCommandAnalyticsRoute: typeof CommandCommandAnalyticsRoute
  CommandCommandAuditRoute: typeof CommandCommandAuditRoute
  CommandCommandCurrencyRoute: typeof CommandCommandCurrencyRoute
  CommandCommandEvidenceRoute: typeof CommandCommandEvidenceRoute
  CommandCommandGeoRoute: typeof CommandCommandGeoRoute
  CommandCommandInvestigationsRoute: typeof CommandCommandInvestigationsRoute
  CommandCommandNetworkRoute: typeof CommandCommandNetworkRoute
  CommandCommandReportsRoute: typeof CommandCommandReportsRoute
  CommandCommandThreatFeedRoute: typeof CommandCommandThreatFeedRoute
  CommandCommandIndexRoute: typeof CommandCommandIndexRoute
}

const CommandRouteChildren: CommandRouteChildren = {
  CommandCommandAdminRoute: CommandCommandAdminRoute,
  CommandCommandAiHealthRoute: CommandCommandAiHealthRoute,
  CommandCommandAnalyticsRoute: CommandCommandAnalyticsRoute,
  CommandCommandAuditRoute: CommandCommandAuditRoute,
  CommandCommandCurrencyRoute: CommandCommandCurrencyRoute,
  CommandCommandEvidenceRoute: CommandCommandEvidenceRoute,
  CommandCommandGeoRoute: CommandCommandGeoRoute,
  CommandCommandInvestigationsRoute: CommandCommandInvestigationsRoute,
  CommandCommandNetworkRoute: CommandCommandNetworkRoute,
  CommandCommandReportsRoute: CommandCommandReportsRoute,
  CommandCommandThreatFeedRoute: CommandCommandThreatFeedRoute,
  CommandCommandIndexRoute: CommandCommandIndexRoute,
}

const CommandRouteWithChildren =
  CommandRoute._addFileChildren(CommandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRouteWithChildren,
  CommandRoute: CommandRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  DemoRoute: DemoRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  TransparencyRoute: TransparencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
